# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  码农学技术
subtitle: 学习技术，思考人生
name: 码农学技术 
email: 953103022@qq.com
description: 本站是我的技术分享博客。内容涵盖 Java后端技术、Spring Boot、Spring Cloud、微服务架构、大数据演进、高可用架构、中间件使用、系统监控等相关的研究与知识分享
keywords: Java,Jvm,Spring,Spring Boot,Spring Cloud,Redis,Mq,MongoDB,FastDFS,Docker,架构,大数据,Python
encoding: "utf-8"
favicon: favicon.ico 

repository: wdsheng0i/wdsheng0i.github.io
github_url: https://github.com/wdsheng0i
url: http://www.wdsheng0i.github.io

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 12
paginate_path: 'page:num'

# Navigation. top menu list
menus:
#  -
#    href: /life.html
#    label: 生活
#    target: _self
  -
    href: /link.html
    label: 友情链接
    target: _self

  -
    href: /about.html
    label: 关于作者
    target: _self
  
  -
    href: https://github.com/wdsheng0i
    label: github
    target: _self 

# Navigation. main menu list
navs:

  -
    href: /
    label: Home

  -
    href: /java.html
    label: Java开发
    target: _blank
    subnav:
        
      -
        subHref: /java-basic.html
        subLabel: Java基础
        target: _self

      -
        subHref: /jvm.html
        subLabel: Jvm原理
        target: _self

      -
        subHref: /juc.html
        subLabel: Java并发
        target: _self

      -
        subHref: /design-patterns.html
        subLabel: 设计原则&设计模式
        target: _self

      -
        subHref: /spring.html
        subLabel: Spring
        target: _self

      -
        subHref: /spring-boot.html
        subLabel: Spring Boot
        target: _self
        
      -
        subHref: /spring-cloud.html
        subLabel: Spring Cloud
        target: _self
  
  -
    href: /arch.html
    label: 架构
    target: _self

  -
    href: /dev-ops.html
    label: Dev&Ops
    target: _self

  -
    href: /python.html
    label: Python
    target: _self

  -
    href: /archives.html
    label: Archives
    target: _self



# labels. my blog key words
#labels:

#  -
#    href: /open-source.html
#    label: Code  
#    target: _blank


# selected articles
classes:

  -
    href: /java.html
    name: java开发
    describe: just do java




# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]

